In [89]:
import pandas as pd
import numpy as np

In [90]:
model_df = pd.read_csv(
    "../data/processed/final_model_df_v2.csv"
)

print(model_df.shape)

(1169, 89)

In [91]:
model_df.head()

,match_id,Unnamed: 0,date,match_type,event_name,innings,batting_team_x,bowling_team,over,ball,...,team1_avg_wickets_last5,team2_avg_runs_last5,team2_avg_wickets_last5,runs_diff,wickets_diff,team1_h2h_win_pct,team2_h2h_win_pct,h2h_diff,venue_avg_score,venue_match_count
0,335982,141607,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,...,5.848259,158.727197,5.848259,0.000000,0.000000,0.5,0.5,0.0,315.225806,62
1,335983,141832,2008-04-19,T20,Indian Premier League,1,Chennai Super Kings,Kings XI Punjab,0,1,...,5.848259,158.727197,5.848259,0.000000,0.000000,0.5,0.5,0.0,313.914286,35
2,335984,142080,2008-04-19,T20,Indian Premier League,1,Rajasthan Royals,Delhi Daredevils,0,1,...,5.848259,158.727197,5.848259,0.000000,0.000000,0.5,0.5,0.0,311.271186,59
3,335985,142299,2008-04-20,T20,Indian Premier League,1,Mumbai Indians,Royal Challengers Bangalore,0,1,...,5.848259,82.000000,10.000000,76.727197,-4.151741,0.5,0.5,0.0,320.361111,72
4,335986,142545,2008-04-20,T20,Indian Premier League,1,Deccan Chargers,Kolkata Knight Riders,0,1,...,5.848259,222.000000,3.000000,-63.272803,2.848259,0.5,0.5,0.0,307.246753,77

In [92]:
print(model_df.columns.tolist())

['match_id', 'Unnamed: 0', 'date', 'match_type', 'event_name', 'innings', 'batting_team_x', 'bowling_team', 'over', 'ball', 'ball_no', 'batter', 'bat_pos', 'runs_batter', 'balls_faced', 'bowler', 'valid_ball', 'runs_extras', 'runs_total', 'runs_bowler', 'runs_not_boundary', 'extra_type', 'non_striker', 'non_striker_pos', 'wicket_kind', 'player_out', 'fielders', 'runs_target', 'review_batter', 'team_reviewed', 'review_decision', 'umpire', 'umpires_call', 'player_of_match', 'match_won_by', 'win_outcome', 'toss_winner', 'toss_decision', 'venue', 'city', 'day', 'month', 'year', 'season', 'gender', 'team_type', 'superover_winner', 'result_type', 'method', 'balls_per_over', 'overs', 'event_match_no', 'stage', 'match_number', 'team_runs', 'team_balls', 'team_wicket', 'new_batter', 'power_surge_start', 'batter_runs', 'batter_balls', 'bowler_wicket', 'batting_partners', 'next_batter', 'striker_out', 'winner_historical_win_pct', 'team1', 'team2', 'team1_win', 'team1_elo', 'team2_elo', 'elo_diff', 'team1_form', 'team2_form', 'form_diff', 'team1_won_toss', 'team2_won_toss', 'batting_team_y', 'team1_avg_runs_last5', 'team1_avg_wickets_last5', 'team2_avg_runs_last5', 'team2_avg_wickets_last5', 'runs_diff', 'wickets_diff', 'team1_h2h_win_pct', 'team2_h2h_win_pct', 'h2h_diff', 'venue_avg_score', 'venue_match_count']

In [93]:
required_features = [
    'team1_elo',
    'team2_elo',

    'team1_form',
    'team2_form',

    'team1_won_toss',

    'team1_avg_runs_last5',
    'team2_avg_runs_last5',

    'team1_avg_wickets_last5',
    'team2_avg_wickets_last5',

    'team1_h2h_win_pct',
    'team2_h2h_win_pct',

    'venue_avg_score',
    'venue_match_count',

    'team1_win'
]

In [94]:
for col in required_features:
    print(
        f"{col}:",
        col in model_df.columns
    )

team1_elo: True
team2_elo: True
team1_form: True
team2_form: True
team1_won_toss: True
team1_avg_runs_last5: True
team2_avg_runs_last5: True
team1_avg_wickets_last5: True
team2_avg_wickets_last5: True
team1_h2h_win_pct: True
team2_h2h_win_pct: True
venue_avg_score: True
venue_match_count: True
team1_win: True

In [95]:
missing = [
    col for col in required_features
    if col not in model_df.columns
]

missing

[]

In [96]:
features = [
    'team1_elo',
    'team2_elo',

    'team1_form',
    'team2_form',

    'team1_won_toss',

    'team1_avg_runs_last5',
    'team2_avg_runs_last5',

    'team1_avg_wickets_last5',
    'team2_avg_wickets_last5',

    'team1_h2h_win_pct',
    'team2_h2h_win_pct',

    'venue_avg_score',
    'venue_match_count'
]

In [97]:
X = model_df[features].copy()

y = model_df['team1_win']

In [98]:
print(X.shape)

X.head()

(1169, 13)

,team1_elo,team2_elo,team1_form,team2_form,team1_won_toss,team1_avg_runs_last5,team2_avg_runs_last5,team1_avg_wickets_last5,team2_avg_wickets_last5,team1_h2h_win_pct,team2_h2h_win_pct,venue_avg_score,venue_match_count
0,1500.0,1500.0,0.5,0.5,0,158.727197,158.727197,5.848259,5.848259,0.5,0.5,315.225806,62
1,1500.0,1500.0,0.5,0.5,1,158.727197,158.727197,5.848259,5.848259,0.5,0.5,313.914286,35
2,1500.0,1500.0,0.5,0.5,1,158.727197,158.727197,5.848259,5.848259,0.5,0.5,311.271186,59
3,1500.0,1484.0,0.5,0.0,1,158.727197,82.000000,5.848259,10.000000,0.5,0.5,320.361111,72
4,1500.0,1516.0,0.5,1.0,1,158.727197,222.000000,5.848259,3.000000,0.5,0.5,307.246753,77

In [99]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print(X_train.shape)
print(X_test.shape)

(935, 13)
(234, 13)

In [100]:
from sklearn.linear_model import LogisticRegression

lr_model = LogisticRegression(
    max_iter=1000,
    random_state=42
)

lr_model.fit(X_train, y_train)

c:\Users\Om Mishra\.conda\envs\cv_env\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(max_iter=1000, random_state=42)

In [101]:
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(
    n_estimators=300,
    max_depth=6,
    random_state=42
)

rf_model.fit(X_train, y_train)

RandomForestClassifier(max_depth=6, n_estimators=300, random_state=42)

In [102]:
from sklearn.ensemble import GradientBoostingClassifier

gb_model = GradientBoostingClassifier(
    n_estimators=200,
    learning_rate=0.05,
    random_state=42
)

gb_model.fit(X_train, y_train)

GradientBoostingClassifier(learning_rate=0.05, n_estimators=200,
                           random_state=42)

In [103]:
from xgboost import XGBClassifier

xgb_model = XGBClassifier(
    n_estimators=300,
    max_depth=4,
    learning_rate=0.05,
    random_state=42
)

xgb_model.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.05, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=4,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=300,
              n_jobs=None, num_parallel_tree=None, ...)

In [104]:
from sklearn.metrics import (
    accuracy_score,
    roc_auc_score
)

In [105]:
models = {
    "Logistic Regression": lr_model,
    "Random Forest": rf_model,
    "Gradient Boosting": gb_model,
    "XGBoost": xgb_model
}

In [106]:
results = []

In [107]:
for name, model in models.items():

    pred = model.predict(X_test)

    prob = model.predict_proba(X_test)[:, 1]

    acc = accuracy_score(
        y_test,
        pred
    )

    auc = roc_auc_score(
        y_test,
        prob
    )

    results.append(
        [name, acc, auc]
    )

In [108]:
comparison = pd.DataFrame(
    results,
    columns=[
        "Model",
        "Accuracy",
        "ROC_AUC"
    ]
)

comparison.sort_values(
    "Accuracy",
    ascending=False
)

                 Model  Accuracy   ROC_AUC
0  Logistic Regression  0.525641  0.502539
3              XGBoost  0.504274  0.517919
1        Random Forest  0.500000  0.495327
2    Gradient Boosting  0.495726  0.492972